

development:
  url: "http://192.168.0.38:3000/recvWord"
  
  keyword:
    -"あひる"
    -"いぬ"
    -"うし"
    -"えび"
    -"おかめ"
    -"かえる"
    -"きつつき"
    -"くま"
    -"けがに"
    -"こい"
    -"さしみ"
    -"しらす"
    -"せみ"
    -"そば"
    -"たぬき"
    -"ちーたあ"
    -"つる"
    -"て"
    -"とぐろ"
    -"なす"
    -"にら"
    -"ぬま"
    -"ねこ"
    -"のり"
    -"はり"
    -"ひ"
    -"ふすま"
    -"へら"
    -"ほ"
    -"ます"
    -"みみずく"
    -"めだか"
    -"もぐら"
    -"やし"
    -"ゆ"
    -"よっと"
    -"わに"
    -"を"
    -"ん"


production:
  url: "http://www.agile.ruby.jp/asayama/recvWord"